### ISSUE TITLE
Wrong data format in file initial_data_path file on Windows

### ISSUE THREAD

**Issue by leybodv** [leybodv/pycatalicism#1]
**To reproduce**
`pycat --conversion D:\path\to\data-dir D:\path\to\initial-data-file co2-hydrogenation`

The above code run on Windows raises ParserException: Wrong data format in file D:\path\to\initial-data-file

**Comment by leybodv** [comment]
On Windows 10:

`pycat calc --conversion --selectivity --output-data ./results --output-plot ./results --sample-name vl120 . .\20230331_init.txt co2-hydrogenation`

> Traceback (most recent call last):
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\calc\chromatec_crystal_composition_copy_paste_parser.py", line 136, in _parse_file
>     file_contents = self._replace_commas_with_dots(path)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\calc\chromatec_crystal_composition_copy_paste_parser.py", line 191, in _replace_commas_with_dots
>     contents = file.read()
>                ^^^^^^^^^^^
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 28: character maps to <undefined>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Scripts\pycat.exe\__main__.py", line 7, in <module>
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\pycat.py", line 623, in main
>     args.func(args)
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\pycat.py", line 37, in calculate
>     calc.calculate(input_data_path=args.input_data_path, initial_data_path=args.initial_data_path, reaction=args.reaction, parser_type=parser_type, calculate_conversion=args.conversion, calculate_selectivity=args.selectivity, products_basis=args.products_basis, output_data_path=args.output_data, show_plot=args.show_plot, output_plot_path=args.output_plot, sample_name=args.sample_name)
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\calc\calc.py", line 65, in calculate
>     input_data = parser.parse_data(Path(input_data_path).resolve(), Path(initial_data_path).resolve(), sample_name)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\calc\chromatec_crystal_composition_copy_paste_parser.py", line 69, in parse_data
>     _, Cs_i, Ta_i, Pa_i, f_i = self._parse_file(initial_data_path)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\d\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycatalicism\calc\chromatec_crystal_composition_copy_paste_parser.py", line 138, in _parse_file
>     raise ParserException(f'Non unicode file {path}')
> pycatalicism.calc.parserexception.ParserException: Non unicode file C:\Users\d\vl120\20230331_init.txt
