### ISSUE TITLE
ChromatographStateException: Chromatograph is not ready to start analysis

### ISSUE THREAD

**Issue by leybodv** [leybodv/pycatalicism#17]
`pycat measure-init-concentration --config path\to\init_conc_config.py`

> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\Scripts\pycat.exe\__main__.py", line 7, in <module>
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\pycat.py", line 560, in main
>     args.func(args)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\pycat.py", line 442, in measure_init_conc
>     chromatograph.start_analysis()
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\chromatograph\chromatec_crystal_5000.py", line 128, in start_analysis
>     raise ChromatographStateException('Chromatograph is not ready to start analysis')
> pycatalicism.chromatograph.chromatograph_exceptions.ChromatographStateException: Chromatograph is not ready to start analysis

**Comment by leybodv** [comment]
`pycat measure-init-concentration --config path\to\init_conc_config.py`

> [23.09.2022 16:52:08] ChromatecControlPanelModbus.get_current_working_status: WARNING: Error during communication with control panel. Trying to reconnect. Trial #1
> [23.09.2022 16:52:12] ChromatecControlPanelModbus.get_current_working_status: WARNING: Error during communication with control panel. Trying to reconnect. Trial #2
> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\chromatograph\chromatec_control_panel_modbus.py", line 94, in get_current_working_status
>     response_registers = response.registers
> AttributeError: 'ModbusIOException' object has no attribute 'registers'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\plotters\process_plotter.py", line 50, in run
>     temperature_point, chromatograph_point, flow_rate_points = self._collect_data()
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\plotters\process_plotter.py", line 80, in _collect_data
>     t = round((time.time() - self._start_time) / 60.0, 2) - round(self._chromatograph.get_analysis_time(), 2)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\chromatograph\chromatec_crystal_5000.py", line 212, in get_analysis_time
>     working_status = self._control_panel.get_current_working_status()
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\chromatograph\chromatec_control_panel_modbus.py", line 98, in get_current_working_status
>     raise ChromatographException('Cannot get working status!')
> pycatalicism.chromatograph.chromatograph_exceptions.ChromatographException: Cannot get working status!

**Comment by leybodv** [comment]
Read and write chromatograph modbus registers with threading.lock
