### ISSUE TITLE
"Wrong receipt from the device" exception

### ISSUE THREAD

**Issue by leybodv** [leybodv/pycatalicism#19]
When non-integer temperature is set for temperature controller, "Wrong receipt from device" exception is thrown due to errors in float point number conversion

**Comment by leybodv** [comment]
Setting temperature to 13.3°C:

> PS C:\Users\User> pycat furnace set-temperature 13.3
> [22.02.2023 17:47:23] OwenTPM101.connect: INFO: Connecting to temperature controller.
> [22.02.2023 17:47:23] OwenTPM101.set_temperature: INFO: Setting temperature to 13.3°C
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_protocol.py", line 157, in send_PIC
>     self._change_parameter_value(message=message)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_protocol.py", line 217, in _change_parameter_value
>     raise FurnaceProtocolException('Got wrong receipt from device!')
> pycatalicism.furnace.furnace_exceptions.FurnaceProtocolException: Got wrong receipt from device!
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\Scripts\pycat.exe\__main__.py", line 7, in <module>
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\pycat.py", line 623, in main
>     args.func(args)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\pycat.py", line 49, in furnace_set_temperature
>     furnace_controller.set_temperature(temperature)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_tmp101.py", line 58, in set_temperature
>     self._owen_protocol.send_PIC(parameter='sp', value=temperature)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_protocol.py", line 161, in send_PIC
>     raise FurnaceConnectionException(ex)
> pycatalicism.furnace.furnace_exceptions.FurnaceConnectionException: Got wrong receipt from device!

Setting to values in 0.5 step seems to be ok:

> PS C:\Users\User> pycat furnace set-temperature 13.5
> [22.02.2023 17:51:19] OwenTPM101.connect: INFO: Connecting to temperature controller.
> [22.02.2023 17:51:19] OwenTPM101.set_temperature: INFO: Setting temperature to 13.5°C
> [22.02.2023 17:51:20] OwenTPM101.set_temperature_control: INFO: Setting temperature control to True
> PS C:\Users\User> pycat furnace set-temperature 13.0
> [22.02.2023 17:51:33] OwenTPM101.connect: INFO: Connecting to temperature controller.
> [22.02.2023 17:51:33] OwenTPM101.set_temperature: INFO: Setting temperature to 13.0°C
> [22.02.2023 17:51:33] OwenTPM101.set_temperature_control: INFO: Setting temperature control to True
> PS C:\Users\User> pycat furnace set-temperature 14.5
> [22.02.2023 17:51:46] OwenTPM101.connect: INFO: Connecting to temperature controller.
> [22.02.2023 17:51:46] OwenTPM101.set_temperature: INFO: Setting temperature to 14.5°C
> [22.02.2023 17:51:47] OwenTPM101.set_temperature_control: INFO: Setting temperature control to True

So need to round correspondingly.
