### ISSUE TITLE
Exceptions during heating

### ISSUE THREAD

**Issue by leybodv** [leybodv/pycatalicism#3]
Started heating with following command:
`python .\pycat.py heat --wait 600 --export-plot D:\CO2-hydrogenation\2022\07\20220728_sup4-5Fe@ZrLaO\activation.png 500`

Target temperature has been reached:

> [27.07.2022 16:26:13] Owen_TPM101_Controller.handshake: INFO: Handshaking with the controller
> [27.07.2022 16:26:13] Owen_TPM101_Controller.heat: INFO: Heating furnace to 500°C
> [27.07.2022 16:52:51] Owen_TPM101_Controller.heat: INFO: Reached target temperature
> [27.07.2022 16:52:51] Owen_TPM101_Controller.heat: INFO: Starting isothermal step for 600 min

Exception was thrown during isothermal step:

> Exception in thread Thread-1 (_request_temperature_data):
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 152, in _request_temperature_data
>     response = self._get_response(message)
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 408, in _get_response
>     response = self._read_message()
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 639, in _read_message
>     if message[0] != chr(0x23) or message[-1] != chr(0x0d):
> IndexError: string index out of range

It seems that isothermal step was finished successfully:

> [28.07.2022 02:52:47] Owen_TPM101_Controller.heat: INFO: Finished isothermal step
> [28.07.2022 02:52:47] SimpleTempTimePlotter.export_plot: INFO: Exporting temperature vs. time plot to D:\CO2-hydrogenation\2022\07\20220728_sup4-5Fe@ZrLaO\activation.png

But another exception was thrown during export of T vs. t plot:

> Traceback (most recent call last):
>   File "D:\git\pycatalicism\pycat.py", line 56, in <module>
>     args.func(args)
>   File "D:\git\pycatalicism\pycat.py", line 28, in heat
>     furnace_module.heat(temperature=args.temperature, wait=args.wait, show_plot=args.show_plot, export_plot=args.export_plot, export_data=args.export_data)
>   File "D:\git\pycatalicism\furnace\furnace_module.py", line 51, in heat
>     plotter.export_plot(data, Path(export_plot).resolve(), fig_dpi, fig_height, fig_width)
>   File "D:\git\pycatalicism\furnace\simple_temp_time_plotter.py", line 55, in export_plot
>     ax = self._get_ax(data, ax)
>   File "D:\git\pycatalicism\furnace\simple_temp_time_plotter.py", line 78, in _get_ax
>     x = data.get_times()
> AttributeError: 'NoneType' object has no attribute 'get_times'

**Comment by leybodv** [comment]
In addition, exception duting heating step can occur.
Started heating with the command:
`python .\pycat.py heat 320`

Heating started successfully:

> [28.07.2022 15:07:30] Owen_TPM101_Controller.handshake: INFO: Handshaking with the controller
> [28.07.2022 15:07:30] Owen_TPM101_Controller.heat: INFO: Heating furnace to 320°C

During heating an exception occurred:

> Traceback (most recent call last):
>   File "D:\git\pycatalicism\pycat.py", line 56, in <module>
>     args.func(args)
>   File "D:\git\pycatalicism\pycat.py", line 28, in heat
>     furnace_module.heat(temperature=args.temperature, wait=args.wait, show_plot=args.show_plot, export_plot=args.export_plot, export_data=args.export_data)
>   File "D:\git\pycatalicism\furnace\furnace_module.py", line 45, in heat
>     data = controller.heat(int(temperature), wait)
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 82, in heat
>     self._wait_until_target_temperature(temperature)
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 173, in _wait_until_target_temperature
>     response = self._get_response(message)
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 408, in _get_response
>     response = self._read_message()
>   File "D:\git\pycatalicism\furnace\owen_tpm101_controller.py", line 640, in _read_message
>     raise FurnaceException(f'Unexpected format of message got from device: {message}')
> pycatalicism.furnace.furnace_exception.FurnaceException: Unexpected format of message got from device: JPSRQQHPM

**Comment by leybodv** [comment]
Added 3 trials of communication when this fail occurs. Seems that workaround helped.

**Comment by leybodv** [comment]
pycatalicism version 0.2.2:

`pycat measure --config path\to\measurement_config.py`

results in exception:

> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\Scripts\pycat.exe\__main__.py", line 7, in <module>
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\pycat.py", line 531, in main
>     args.func(args)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\pycat.py", line 343, in measure
>     current_temperature = furnace.get_temperature()
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_tmp101.py", line 77, in get_temperature
>     temperature = self._owen_protocol.request_PIC(parameter='pv')
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_protocol.py", line 118, in request_PIC
>     parameter_data_bytes = self._get_parameter_data_bytes(message)
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_protocol.py", line 236, in _get_parameter_data_bytes
>     response = self._read_message()
>   File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pycatalicism\furnace\owen_protocol.py", line 283, in _read_message
>     if message[0] != chr(0x23) or message[-1] != chr(0x0d):
> IndexError: string index out of range
