### ISSUE TITLE
AttributeError: 'ExceptionResponse' object has no attribute 'registers'

### ISSUE THREAD

**Issue by leybodv** [leybodv/pycatalicism#4]
`python .\pycat.py chromatograph connect`

results in:

> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_current_working_status: DEBUG: Getting current working status of chromatograph
> [16.08.2022 09:43:40] pycatalicism.chromatograph.modbus_converter.bytes_to_int: DEBUG: Converting bytes: [0, 0] to int
> [16.08.2022 09:43:40] pycatalicism.chromatograph.modbus_converter.bytes_to_int: Level 5: integer = 0
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_current_working_status: Level 5: current_status = <WorkingStatus.NULL: 0>
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_current_working_status: DEBUG: Getting current working status of chromatograph
> [16.08.2022 09:43:40] pycatalicism.chromatograph.modbus_converter.bytes_to_int: DEBUG: Converting bytes: [0, 0] to int
> [16.08.2022 09:43:40] pycatalicism.chromatograph.modbus_converter.bytes_to_int: Level 5: integer = 0
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_current_working_status: Level 5: current_status = <WorkingStatus.NULL: 0>
> [16.08.2022 09:43:40] ChromatecCrystal5000.connect: INFO: Starting control panel application
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.send_application_command: DEBUG: Sending command to control panel: ApplicationCommand.START_CONTROL_PANEL
> [16.08.2022 09:43:40] ChromatecCrystal5000.connect: INFO: Waiting until control panel is up...
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:40] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:40] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:42] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:42] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:42] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:43] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:43] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:43] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:44] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:44] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:44] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:45] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:45] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:45] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:46] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:46] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:46] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:47] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:47] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:47] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:48] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:48] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:48] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:49] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:49] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:49] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:50] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:50] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:50] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:51] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:51] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:51] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:52] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:52] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:52] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:53] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:53] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:53] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:54] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:54] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:54] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:55] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:55] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:55] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:56] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:56] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:56] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:57] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 09:43:57] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:57] ChromatecCrystal5000.connect: DEBUG: self._connection_status = <ConnectionStatus.CP_OFF_NOT_CONNECTED: 0>
> [16.08.2022 09:43:58] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> Traceback (most recent call last):
>   File "D:\git-test\pycatalicism\pycat.py", line 113, in <module>
>     args.func(args)
>   File "D:\git-test\pycatalicism\pycat.py", line 38, in chromatograph_connect
>     chromatograph.connect()
>   File "D:\git-test\pycatalicism\chromatograph\chromatec_crystal_5000.py", line 46, in connect
>     self._connection_status = self._control_panel.get_connection_status()
>   File "D:\git-test\pycatalicism\chromatograph\chromatec_control_panel_modbus.py", line 117, in get_connection_status
>     connection_status = ConnectionStatus(response.registers[0])
> AttributeError: 'ExceptionResponse' object has no attribute 'registers'

When connection status request period was changed to 10 s, everything was ok

**Comment by leybodv** [comment]
`python .\pycat.py chromatograph set-method purge`

results in similar traceback:

> [16.08.2022 09:47:39] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> Traceback (most recent call last):
>   File "D:\git-test\pycatalicism\pycat.py", line 66, in <module>
>     chromatograph = ChromatecCrystal5000(control_panel_modbus, analytic_modbus, config.methods)
>   File "D:\git-test\pycatalicism\chromatograph\chromatec_crystal_5000.py", line 27, in __init__
>     self._connection_status = self._control_panel.get_connection_status()
>   File "D:\git-test\pycatalicism\chromatograph\chromatec_control_panel_modbus.py", line 117, in get_connection_status
>     connection_status = ConnectionStatus(response.registers[0])
> AttributeError: 'ModbusIOException' object has no attribute 'registers'

**Comment by leybodv** [comment]
Seems to work now
