### ISSUE TITLE
struct.error: unpack requires a buffer of 54 bytes

### ISSUE THREAD

**Issue by leybodv** [leybodv/pycatalicism#6]
`python .\pycat.py chromatograph set-passport --name 20220816_purge --operator leybo --column NaX/HaesepN`

results in traceback:

> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_ON_CONNECTED: 7>
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_current_working_status: DEBUG: Getting current working status of chromatograph
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.bytes_to_int: DEBUG: Converting bytes: [6, 0] to int
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.bytes_to_int: Level 5: integer = 6
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_current_working_status: Level 5: current_status = <WorkingStatus.PURGING: 6>
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_connection_status: DEBUG: Getting chromatograph and control panel connection status
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_connection_status: Level 5: connection_status = <ConnectionStatus.CP_ON_CONNECTED: 7>
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_current_working_status: DEBUG: Getting current working status of chromatograph
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.bytes_to_int: DEBUG: Converting bytes: [6, 0] to int
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.bytes_to_int: Level 5: integer = 6
> [16.08.2022 10:48:12] ChromatecControlPanelModbus.get_current_working_status: Level 5: current_status = <WorkingStatus.PURGING: 6>
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_sample_name: DEBUG: Setting chromatogram name to 20220816_purge
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: DEBUG: Converting string 20220816_purge to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: string_bytes = b'20220816_purge'
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: message = (12848, 12850, 12344, 12598, 24432, 30066, 26469)
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_sample_volume: DEBUG: Setting sample volume to 0.5
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.double_to_bytes: DEBUG: Converting double 0.5 to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.double_to_bytes: Level 5: double_bytes = b'\x00\x00\x00\x00\x00\x00\xe0?'
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.double_to_bytes: Level 5: message = (0, 0, 0, 16352)
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_sample_dilution: DEBUG: Setting sample dilution to 1.0
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.double_to_bytes: DEBUG: Converting double 1.0 to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.double_to_bytes: Level 5: double_bytes = b'\x00\x00\x00\x00\x00\x00\xf0?'
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.double_to_bytes: Level 5: message = (0, 0, 0, 16368)
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_chromatogram_purpose: DEBUG: Setting chromatogram purpose to ChromatogramPurpose.ANALYSIS
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.int_to_bytes: DEBUG: Converting integer 0 to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.int_to_bytes: Level 5: integer_bytes = [0]
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_operator: DEBUG: Setting operator to leybo
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: DEBUG: Converting string leybo to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: string_bytes = b'leybo\x00'
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: message = (27749, 31074, 28416)
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_column: DEBUG: Setting column to NaX/HaesepN
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: DEBUG: Converting string NaX/HaesepN to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: string_bytes = b'NaX/HaesepN\x00'
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: message = (20065, 22575, 18529, 25971, 25968, 19968)
> [16.08.2022 10:48:12] ChromatecAnalyticModbus.set_lab_name: DEBUG: Setting laboratory name to Неорганические наноматериалы
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: DEBUG: Converting string Неорганические наноматериалы to bytes
> [16.08.2022 10:48:12] pycatalicism.chromatograph.modbus_converter.string_to_bytes: Level 5: string_bytes = b'\xd0\x9d\xd0\xb5\xd0\xbe\xd1\x80\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd1\x8b'
> Traceback (most recent call last):
>   File "D:\git-test\pycatalicism\pycat.py", line 113, in <module>
>     args.func(args)
>   File "D:\git-test\pycatalicism\pycat.py", line 62, in chromatograph_set_passport
>     chromatograph.set_passport(name=args.name, volume=float(args.volume), dilution=float(args.dilution), purpose=purpose, operator=args.operator, column=args.column, lab_name=args.lab_name)
>   File "D:\git-test\pycatalicism\chromatograph\chromatec_crystal_5000.py", line 176, in set_passport
>     self._analytic.set_lab_name(lab_name)
>   File "D:\git-test\pycatalicism\chromatograph\chromatec_analytic_modbus.py", line 142, in set_lab_name
>     name_bytes = convert.string_to_bytes(name)
>   File "D:\git-test\pycatalicism\chromatograph\modbus_converter.py", line 71, in string_to_bytes
>     message = struct.unpack('>'+'H'*int(len(string_bytes)/2), string_bytes)
> struct.error: unpack requires a buffer of 54 bytes

**Comment by leybodv** [comment]
`python .\pycat.py chromatograph set-passport --name 20220816_purge --operator leybo --column NaX/HaesepN --lab-name "Inorganic Nanomaterials"`

was successful
